### ISSUE TITLE
NewSoftSerial is now SoftwareSerial in Arduino 1.0 and up

### ISSUE THREAD

**Issue by f3ndot** [sparkfun/SM5100B_Cellular_Shield#1]
The current sketch works for older IDEs but if you have Arduino 1.0 or higher `NewSoftSerial` has been incorporated into core as `SoftwareSerial`.

The sketch should probably be updated to reflect that, or something. Also update the extension to `.ino`.

See: http://arduiniana.org/libraries/NewSoftSerial/

**Comment by bboyho** [comment]
Hi,

Thanks of the comment. A note has been added to the page and it was a quick fix since it was just a serial passthrough. Unfortunately, the product has been retired so this product repo will also be retired.
