### ISSUE TITLE
Coincell package choice

### ISSUE THREAD

**Issue by lewispg228** [sparkfun/SM5100B_Cellular_Shield#5]
I think the PTH legs will conflict with the module sitting flush with the PCB. Maybe we should go with the SMD package?

**Comment by ToniCorinne** [comment]
My only thought against that is the module torques against the connector as it is currently. Could this help prevent it? Figured it was worth checking out on a protoype, but if you think it's going to be that bad, I can change it.

**Comment by lewispg228** [comment]
Now that I think about it, I'm more worried about the metal on the bottom side of the module shorting out the battery. It's probably safest to go SMD.

![image](https://cloud.githubusercontent.com/assets/601236/5209627/3d87f57a-757e-11e4-9d56-aa629d27b265.png)

**Comment by ToniCorinne** [comment]
Swapped.
