### ISSUE TITLE
Schematic Cleanup

### ISSUE THREAD

**Issue by lewispg228** [sparkfun/SM5100B_Cellular_Shield#6]
1) GND net wire off of arduino shield symbol is 8 mil, should be 6

2) Delete unused net wires and flags off of arduino shield symbol.

3) On the jumpers that control RX/TX, the default settings seem weird to me. It's split between Hardware RX and Software TX (on D3).  Wouldn't it make more sense to default entirely to the hardware RX/TX? Maybe this is left over from Ryan's original design?

4) Delete unnecessary labels on "EAR" pins off of cell module symbol. Scoot JP5 down so the net wires go directly from pins to pins (no need for extra kinks).

5) Remove unnecessary kink in GND net off of S1.

6) LED1 needs to be D1

7) solder jumper prefixes should be SJ

8) Remove value on JP7 and S1

**Comment by ToniCorinne** [comment]
Not sure what you mean by unnecessary labels on EAR pins. I did the same on RTC_Batt. If I'm missing your meaning, let me know. 

All other issues addressed.

**Comment by lewispg228** [comment]
All looks good. Thanks.

About #4, I guess it's fine to leave text labels on those nets. I prefer a super clean schematic, and whenever something isn't necessary, I like to remove it. 

Labeling a net means the designer purposefully named the net which usually means it's connected elsewhere in the schematic. In this case, those net's are not. But it's debatable if those net names are useful or just redundant from the pin names on the symbol.

About #3. I just checked the example sketch on the product page and it does use software serial on D2 and D3 to talk to the module, so I think this is the best default setting to ship with. Thanks for changing this.
