### ISSUE TITLE
Board issues v13

### ISSUE THREAD

**Issue by lewispg228** [sparkfun/SM5100B_Cellular_Shield#7]
1) board dimensions should be 0.008, currently 0.010

2) Move JP7 on grid. For ease of testbed design mostly, but someone may want to use protoboard off the side, and align with nearby arduino 10 pin header.

3) Please add trestrict to the cell module connector GND pads to removed thermal tick traces between GND pads. And then manually route GND from pad directly away into polygon. 

4) re-route 45 degree exit off of upper pad of C6

5) Move logo down so it doesn't get the outline silk cut through it. Also, add flame to upper right corner, so we can see it even after a module has been populated.

6) Outline silk on the cell module (and connector) is too thin.

7) Add bottom silk to label headers on JP5 and JP7

**Comment by ToniCorinne** [comment]
Fixed. 

I did not move JP7 directly next to the Arduino header as there is a screw hole right there that some customers may use on the Arduino itself. It is on grid, but I wanted to leave a bit of room for PTH headers to prevent possible shorting.
